#!/usr/bin/env python
""" --- Pardus Online Paket Yukleme --- """
import os
from pisi.db.installdb import InstallDB

#binary search
def myBinarySearch(seq, t):
  """ Binary Search Algorithm """
  min = 0; max = len(seq) - 1
  while 1:
    if max < min:
      return -1
    m = (min + max) / 2
    if seq[m] < t:
      min = m + 1
    elif seq[m] > t:
      max = m - 1
    else:
      return m

def extractPack():
  """ Gets installed Pisi packages by user named userpacks """
  os.system("echo Getting list of pisi installed packages... ")
  aipf=open("allpacks","w")
  ipdb = InstallDB()
  tempList = ipdb.list_installed()
  tempList.sort()
  for entry in tempList:
    aipf.write(entry + "\n")
  os.system("echo Done!\n")
  
  os.system("echo Put list of pisi installed packages into a list... ")
  allpacks=open("allpacks","r")#put all packages into a list
  allp=[]
  for line in allpacks:    
    packname=line.split()
    allp.append(packname[0])
  allpacks.close()
  os.system("echo Done!\n")
  
  os.system("echo Put list of pisi core packages into another list... ")
  corepacks=open("corepacks","r")#put core packages into another list
  corep=[]
  for line in corepacks:
    packname=line.split()
    corep.append(packname[0])
  corepacks.close()
  os.system("echo Done!\n")
  
  os.system("echo Comparisons... ")
  userpacks=open("userpacks","w")
  #compare lists  
  for line in allp:
    index=myBinarySearch(corep,line)
    if index == -1:
      userpacks.write(line + '\n')
  os.system("echo Done!\n")
  userpacks.close()

def installPack():
  userpacks=open("userpacks","r")
  for line in userpacks:
    #os.system("sudo pisi it -y --reinstall %s" % line)
    os.system("sudo pisi it %s" % line)
  userpacks.close()

def menuPrinting():
  """It prints menu"""
  print '\n' + '=' * 9 + ' MENU ' + '=' * 9
  print '1-Update repository'
  print '2-Update Pisi'
  print '3-Extract package list from Pisi'
  print '4-Setup packages'
  print '0-Exit\n'

def executeCode(ch):
  if ch == 1:
    os.system("sudo pisi ur")
    os.system("echo Checking repository is done!")
  elif ch == 2:
    os.system("sudo pisi up")
    os.system("echo Updating repository is done!")
  elif ch == 3:
    extractPack()
  elif ch == 4:
    installPack()
  elif ch == 0:
    exit()

choice = 1
# menu
while choice != 0:
  menuPrinting()
  choice = raw_input("Select one of them!\t")
  upperchoice=4
  lowerchoice=0
  
  if choice.isdigit() != True:
    os.system("echo WRONG! Enter a NUMBER!\n")
    continue
  elif int(choice) > upperchoice or int(choice) < lowerchoice:
    os.system("echo WRONG! Enter a VALID number!\n")
    continue
  else:
    executeCode(int(choice))